// <auto-generated>This is auto-generated code by DIS. Do not modify.</auto-generated>
using System.ComponentModel;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Skyline.DataMiner.Scripting
{
public static class Parameter
{
	public class Write
	{
		/// <summary>PID: 54 | Type: write</summary>
		[EditorBrowsable(EditorBrowsableState.Never)]
		public const int sendrequest_54 = 54;
		/// <summary>PID: 54 | Type: write</summary>
		public const int sendrequest = 54;
	}
}
public class WriteParameters
{
	/// <summary>PID: 54  | Type: write | DISCREETS: Send Request = Send Request</summary>
	public System.Object Sendrequest {get { return Protocol.GetParameter(54); }set { Protocol.SetParameter(54, value); }}
	public SLProtocolExt Protocol;
	public WriteParameters(SLProtocolExt protocol)
	{
		Protocol = protocol;
	}
}
public interface SLProtocolExt : SLProtocol
{
	object Sendrequest_54 { get; set; }
	object Sendrequest { get; set; }
	WriteParameters Write { get; set; }
}
public class ConcreteSLProtocolExt : ConcreteSLProtocol, SLProtocolExt
{
	/// <summary>PID: 54  | Type: write | DISCREETS: Send Request = Send Request</summary>
	public System.Object Sendrequest_54 {get { return GetParameter(54); }set { SetParameter(54, value); }}
	/// <summary>PID: 54  | Type: write | DISCREETS: Send Request = Send Request</summary>
	public System.Object Sendrequest {get { return Write.Sendrequest; }set { Write.Sendrequest = value; }}
	public WriteParameters Write { get; set; }
	public ConcreteSLProtocolExt()
	{
		Write = new WriteParameters(this);
	}
}
}
